apiVersion: argoproj.io/v1alpha1
kind: Application

metadata:
  name: vote-api
  namespace: argocd

  finalizers:
    - resources-finalizer.argocd.argoproj.io

spec:
  project: default

  source:
    repoURL: https://github.com/Ajju41216/kubernetes-gitops.git
    targetRevision: main
    path: charts/vote

    helm:
      releaseName: vote-api
      valueFiles:
        - values.yaml

  destination:
    server: https://kubernetes.default.svc
    namespace: vote

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
