apiVersion: apps/v1
kind: Deployment

metadata:
  name: {{ include "worker.fullname" . }}

  labels:
    {{- include "worker.labels" . | nindent 4 }}
    app: {{ .Values.labels.app }}
    tier: {{ .Values.labels.tier }}

spec:
  replicas: {{ .Values.replicaCount }}

  revisionHistoryLimit: 5

  strategy:
    type: RollingUpdate

    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1

  selector:
    matchLabels:
      {{- include "worker.selectorLabels" . | nindent 6 }}

  template:
    metadata:
      labels:
        {{- include "worker.selectorLabels" . | nindent 8 }}
        app: {{ .Values.labels.app }}
        tier: {{ .Values.labels.tier }}
        environment: {{ .Values.labels.environment }}
        version: {{ .Values.labels.version }}

    spec:
      containers:
        - name: worker

          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"

          imagePullPolicy: {{ .Values.image.pullPolicy }}

          resources:
            {{- toYaml .Values.resources | nindent 12 }}