replicaCount: 1

image:
  repository: worker
  tag: "01"
  pullPolicy: IfNotPresent

labels:
  app: worker
  tier: backend
  environment: lab
  version: v1

redis:
  host: redis-redis
  port: 6379

database:
  host: postgres
  port: 5432
  name: votes
  user: postgres
  password: postgres

resources:
  requests:
    cpu: 100m
    memory: 128Mi

  limits:
    cpu: 250m
    memory: 256Mi