replicaCount: 2

image:
  repository: worker
  tag: "01"

config:
  redisHost: redis
  redisPort: "6379"

  dbHost: db
  dbPort: "5432"

resources:
  requests:
    cpu: 100m
    memory: 128Mi

  limits:
    cpu: 500m
    memory: 256Mi